import type { Config } from "tailwindcss";

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-sans)', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        mono: ['var(--font-mono)', 'ui-monospace', 'monospace'],
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: "var(--primary)",
        "primary-dark": "var(--primary-hover)",
        "primary-hover": "var(--primary-hover)",
        danger: "#C65B5B",
        "danger-light": "rgba(198, 91, 91, 0.1)",
        warning: "#C6A15B",
        "warning-light": "rgba(198, 161, 91, 0.1)",
        success: "#6B8F71",
        "success-light": "rgba(107, 143, 113, 0.1)",
        neutral: {
          50: "var(--neutral-50)",
          100: "var(--neutral-100)",
          200: "var(--neutral-200)",
          300: "var(--neutral-300)",
          400: "var(--neutral-400)",
          500: "var(--neutral-500)",
          600: "var(--neutral-600)",
          700: "var(--neutral-700)",
          800: "var(--neutral-800)",
          850: "var(--neutral-850)",
          900: "var(--neutral-900)",
          950: "var(--neutral-950)",
        },
        // Remap blue scale to oxide green — replaces generic SaaS blue across all components
        blue: {
          50:  "#F2F5EE",
          100: "#E0E8D6",
          200: "#BFCE9E",
          300: "#A3B67E",
          400: "#93A97A",
          500: "#7C8F62",
          600: "#6B7D53",
          700: "#5E6B4A",
          800: "#4A5539",
          900: "#36402A",
          950: "#222819",
        },
        surface: "var(--surface)",
        "surface-hover": "var(--surface-hover)",
        border: "var(--border)",
        "border-subtle": "var(--border-subtle)",
        accent: "var(--accent)",
        "accent-hover": "var(--accent-hover)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-muted": "var(--text-muted)"
      },
      borderRadius: {
        sm: '6px',
        DEFAULT: '10px',
        md: '10px',
        lg: '10px',
        xl: '12px',
        '2xl': '16px',
      },
      backdropFilter: {
        'none': 'none',
        'blur': 'blur(20px)',
      },
      animation: {
        'spin': 'spin 1s linear infinite',
        'fade-in': 'fadeIn 0.15s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
    },
  },
  plugins: [],
  safelist: [
    'circuit-container',
    'circuit-header',
    'circuit-content',
    'circuit-sidebar',
    'circuit-tabs',
    'circuit-tab',
    'circuit-tab-active',
    'circuit-tab-inactive',
    'circuit-main',
    'circuit-visualization',
    'circuit-status',
    'button-primary',
    'button-secondary',
    'button-success',
    'spider-visualization',
    'spider-plot',
    'spider-svg',
    'spider-card',
    'spider-card-header',
    'spider-value-indicator',
    'spider-heading',
    'spider-label',
    'spider-parameter-label',
    'spider-parameter-name',
    'spider-parameter-value',
    'spider-parameter-unit',
    'spider-reference-dot',
    'spider-grid-line',
    'spider-axis-line',
    'spider-control-label',
    'spider-control-value',
    'spider-range-slider',
    'spider-info-box',
    'spider-info-title',
    'spider-info-row',
    'spider-info-label',
    'param-slider',
    'slider-label',
    'slider-value',
    'slider-input',
    'slider-label-text',
    'slider-tick-label',
    'slider-tick-level',
    'data-table',
    'data-table-header',
    'data-th',
    'data-td',
    'icon-button',
    'card',
    'card-header',
    'collapsible-section',
    'section-header',
    'section-content',
    'text-title',
    'text-subtitle',
    'text-small',
    'text-data',
    {
      pattern: /^(circuit|spider|button|param|slider|data)-.*$/,
    }
  ]
} satisfies Config;
