#!/usr/bin/env python3
"""
Gaussian Particle Filter (GPF) for EIS temporal parameter tracking.

Each particle carries a local Gaussian approximation (mean + full covariance),
updated via an iterated EKF (IEKF) observation step. The ensemble forms an
implicit Gaussian mixture over the parameter posterior.

Version: bio-v1.1
-----------------
Biological dynamics improvements over the original fixed-noise GPF:
  - Bounds expanded to match the full physiological range generated by
    simulation/trajectory_generator.py (Ca/Cb now 3e-7 – 3e-3 F, Ra up to 40 kΩ).
  - Process noise (Q_POS_DIAG) recalibrated: Ca/Cb noise increased 6× to match
    the wider capacitance range; Ra/Rb/Rsh unchanged.
  - Weak biological mean-reversion added to _predict(): kappa ~ 1e-4 /min pulls
    particles toward the literature-derived healthy RPE center.  This is ~100×
    weaker than measurement information — invisible during normal EIS steps but
    prevents unbounded drift during measurement gaps.

v1.1 additions:
  - Vectorized Jacobian: two batch impedance calls of size (D×N, 5) instead of
    10 sequential calls of (N, 5), eliminating the Python loop over dimensions.
    Delivers ~1.7× speedup at F=100 with numerically identical results.
  - Cold start from _HEALTHY_CENTER_LOG10 instead of BOUNDS_MID: removes the
    systematic Rsh underestimation that made cold-start worse than the naive
    healthy-center baseline.

Design
------
Particles live in raw log10 space [Ra, Rb, Ca, Cb, Rsh]. The (Ra,Ca)<->(Rb,Cb) mode
degeneracy is handled implicitly: half the particles are initialized near each mode and
the weights distinguish them over time without a discrete mode variable.

The (Ra,Ca)<->(Rb,Cb) swap gives EXACTLY identical impedance spectra (permutation
symmetry of series RC elements). Therefore the filter assigns equal weights to both modes,
which is physically correct. What matters is the identifiable parameter estimates
(tau_big, tau_small, TER, TEC, Rsh) derived from the particle cloud.

Per-particle state: position only
    theta_t^(i) in R^5 (log10 [Ra, Rb, Ca, Cb, Rsh])
    P_t^(i) in R^{5x5} (position covariance)

Process model (random walk with drift):
    theta_pred = theta_post + v_global * dt + N(0, Q_pos * dt)
    P_pred = P_post + Q_pos * dt

where v_global is a global velocity estimate from the weighted mean displacement,
and Q_pos is the position process noise spectral density (diagonal).

Observation model:
    Z_t = Z(theta_t^(i)) + J_t^(i) dtheta + eps,   eps ~ N(0, sigma2 * I_{2F})
    J_t^(i) = d(Z_norm)/d(log10 theta) evaluated at particle i's position.

Woodbury identity for efficient 5x5 computation instead of 2F x 2F:
    M_i = P_pp_i^{-1} + J_i^T J_i / sigma2   (5x5)
    K_i = M_i^{-1} J_i^T / sigma2             (5 x 2F)
    e^T S_i^{-1} e = ||e||^2/sigma2 - (J_i^T e)^T M_i^{-1} (J_i^T e) / sigma2^2
    log|S_i| = log|M_i| + log|P_pp_i| + 2F * log(sigma2)

Weight update:
    log w_t^(i) += -0.5 * (mahal_i + log|S_i| + 2F * log(2pi))

Interface
---------
    gpf = GaussianParticleFilter(n_particles=64)
    gpf.initialize(ecm_log10=..., mdn_samples=...)
    for t in range(T):
        particles_t, log_ev_t = gpf.step(Z_r_t, Z_i_t, omega, dt)
        particles_history.append(particles_t)
"""

import numpy as np
from typing import Optional

# Version tag — bump when bounds, process noise, or biological priors change.
# Propagated through get_diagnostics() and physics_api /model_info endpoint.
GPF_VERSION = "bio-v1.1"

# Parameter bounds (raw log10): [Ra, Rb, Ca, Cb, Rsh]
# Matched to SIM_BOUNDS in simulation/trajectory_generator.py so the GPF can
# track the full physiological range generated by the trajectory simulator.
BOUNDS_LOW  = np.array([1.699, 1.699, -6.5,  -6.5,  1.699], dtype=np.float64)
BOUNDS_HIGH = np.array([4.602, 4.398, -2.5,  -2.5,  4.602], dtype=np.float64)
BOUNDS_MID  = (BOUNDS_LOW + BOUNDS_HIGH) / 2.0

_LOG_2PI = float(np.log(2 * np.pi))

# Position process noise spectral density (log10^2 / min) — diagonal, no cross terms.
# Calibrated against SDE diffusion in pathology_models.py (BASE_SIGMA = 0.002 log10/√min
# for Ra/Rb/Rsh, 0.0015 for Ca/Cb).  Q values here are intentionally 10–30× larger
# than BASE_SIGMA² to stay data-driven: the measurement likelihood dominates in normal
# operation while Q prevents collapse when data are uninformative.
_Q_POS_DIAG = np.array([
    1.6e-4,   # Ra   (weaker identifiability → allow more diffusion)
    1.6e-4,   # Rb
    6.0e-5,   # Ca   (wider physiological range after bound expansion)
    6.0e-5,   # Cb
    4.9e-4,   # Rsh  (Rsh changes fastest; ~0.022 log10 per 3-min step)
], dtype=np.float64)

# Healthy RPE prior center in log10 [Ra, Rb, Ca, Cb, Rsh] (raw Ω / F).
# Derived from literature (A = 0.11409 cm²):
#   Rb  ≈ 60 Ω·cm²  → 526 Ω   → log10 ≈ 2.72
#   Ra  ≈ 4×Rb      → 2104 Ω  → log10 ≈ 3.32
#   Rsh ≈ 1500 Ω·cm² → 13148 Ω → log10 ≈ 4.12
#   τa  ≈ 0.15s → Ca = τa/Ra ≈ 7.1e-5 F → log10 ≈ -4.15
#   τb  ≈ 0.05s → Cb = τb/Rb ≈ 9.5e-5 F → log10 ≈ -4.02
_HEALTHY_CENTER_LOG10 = np.array([3.32, 2.72, -4.15, -4.02, 4.12], dtype=np.float64)

# Biological mean-reversion rate [log10 / min per log10 deviation].
# At kappa=1e-4, a 2-decade deviation corrects by ~2% over a 10-minute window —
# imperceptible against measurement data but prevents unlimited drift during gaps.
# Uniform across all parameters: doubling Rsh kappa hurt tracking for pathologies
# that decrease Rsh (apical_injury, barrier_breakdown) since the prior pulls the
# wrong direction.
_BIO_KAPPA = np.array([1e-4, 1e-4, 1e-4, 1e-4, 1e-4], dtype=np.float64)


def _impedance_batch_numpy(params_log10: np.ndarray, omega: np.ndarray):
    """
    Vectorized RPE circuit impedance for N particles.

    params_log10: (N, 5) log10 [Ra, Rb, Ca, Cb, Rsh]
    omega:        (F,)   angular frequencies (rad/s)
    Returns: Z_real (N, F), Z_imag (N, F)
    """
    p = 10.0 ** params_log10.astype(np.float64)
    Ra  = p[:, 0:1]; Rb  = p[:, 1:2]
    Ca  = p[:, 2:3]; Cb  = p[:, 3:4]; Rsh = p[:, 4:5]
    w = omega[np.newaxis, :]

    Za_r = Ra / (1 + (w * Ra * Ca) ** 2)
    Za_i = -(w * Ra ** 2 * Ca) / (1 + (w * Ra * Ca) ** 2)
    Zb_r = Rb / (1 + (w * Rb * Cb) ** 2)
    Zb_i = -(w * Rb ** 2 * Cb) / (1 + (w * Rb * Cb) ** 2)

    Zs_r = Za_r + Zb_r
    Zs_i = Za_i + Zb_i
    denom = (Rsh + Zs_r) ** 2 + Zs_i ** 2
    Z_r = (Rsh * Zs_r * (Rsh + Zs_r) + Rsh * Zs_i ** 2) / denom
    Z_i = (Rsh ** 2 * Zs_i) / denom
    return Z_r, Z_i


def _jacobian_numerical(
    particles_log10: np.ndarray,
    omega: np.ndarray,
    norm_r: float,
    norm_i: float,
    eps: float = 2e-3,
) -> np.ndarray:
    """
    Central-difference Jacobian d(Z_norm)/d(log10 theta) for N particles.

    Vectorized: perturbs all D dimensions simultaneously using 2 batch calls of
    size (D*N, 5) instead of 2*D calls of size (N, 5). Eliminates the Python
    for loop over D that was the bottleneck at high frequency counts (F=100+).

    Returns: J (N, 2*F, 5)
    """
    N, D = particles_log10.shape
    F = len(omega)

    # Build (D, N, D) arrays: p_plus[d] perturbs dimension d by +eps
    base = particles_log10[np.newaxis, :, :]               # (1, N, D)
    p_plus  = np.broadcast_to(base, (D, N, D)).copy()      # (D, N, D)
    p_minus = p_plus.copy()
    for d in range(D):
        p_plus[d, :, d]  = np.clip(particles_log10[:, d] + eps, BOUNDS_LOW[d], BOUNDS_HIGH[d])
        p_minus[d, :, d] = np.clip(particles_log10[:, d] - eps, BOUNDS_LOW[d], BOUNDS_HIGH[d])

    # Two batch impedance calls of size (D*N, D) instead of 2*D calls of (N, D)
    Zr_p, Zi_p = _impedance_batch_numpy(p_plus.reshape(D * N, D),  omega)   # (D*N, F)
    Zr_m, Zi_m = _impedance_batch_numpy(p_minus.reshape(D * N, D), omega)   # (D*N, F)

    # dZ shape: (D, N, F) → transpose to (N, F, D) → stack real/imag
    dZr = (Zr_p - Zr_m).reshape(D, N, F).transpose(1, 2, 0) / (2 * eps * norm_r)
    dZi = (Zi_p - Zi_m).reshape(D, N, F).transpose(1, 2, 0) / (2 * eps * norm_i)
    return np.concatenate([dZr, dZi], axis=1)              # (N, 2F, D)


def _ensure_psd(M: np.ndarray, eps: float = 1e-9) -> np.ndarray:
    """Enforce positive definiteness via eigenvalue clipping."""
    M = (M + M.T) / 2
    evals, evecs = np.linalg.eigh(M)
    return evecs @ np.diag(np.clip(evals, eps, None)) @ evecs.T


def ffbs_backward_sweep(
    positions_history: list,
    weights_history:   list,
    P_diag_history:    list,
    dt_history:        list,
) -> list:
    """
    Forward-Filter Backward-Smoother (FFBS) for the Gaussian Particle Filter.

    Given the stored forward-pass state, computes backward-smoothed weights
    s_t^i ≈ p(θ_t^i | y_{1:T}) via the recursion (Briers, Doucet & Maskell 2010):

        s_T^i = w_T^i
        s_t^i = w_t^i · Σ_j [ s_{t+1}^j · τ_ij / Σ_k w_t^k · τ_kj ]

    where the transition density uses the per-particle IEKF posterior width:
        τ_ij = N(θ_{t+1}^j ; θ_t^i, (Q + diag(P_t^i)) · Δt)

    Args:
        positions_history : T × (N, 5) log10 [Ra,Rb,Ca,Cb,Rsh] particle positions
        weights_history   : T × (N,) normalized forward weights at each step
        P_diag_history    : T × (N, 5) diagonal of per-particle covariance P_pp
        dt_history        : T × float Δt in minutes for each step

    Returns:
        smoothed : T × (N,) smoothed (backward-informed) normalized weights
    """
    T = len(positions_history)
    if T < 2:
        return [w.copy() for w in weights_history]

    smoothed: list = [None] * T
    smoothed[-1] = weights_history[-1].copy()

    for t in range(T - 2, -1, -1):
        x_t  = positions_history[t]    # (N, 5)
        x_t1 = positions_history[t+1]  # (N, 5)
        w_t  = weights_history[t]      # (N,)
        P_d  = P_diag_history[t]       # (N, 5)
        dt   = max(float(dt_history[t]), 1e-3)

        # Per-particle transition variance: Σ_t^i = (Q + diag(P_t^i)) · Δt
        # Clamp P_d to avoid negative values from numerical noise
        var_t = (_Q_POS_DIAG + np.maximum(P_d, 0.0)) * dt   # (N, 5)

        # Pairwise diff: diff[i, j, d] = θ_{t+1}^j[d] - θ_t^i[d]
        diff = x_t1[np.newaxis, :, :] - x_t[:, np.newaxis, :]   # (N, N, 5)

        # Log Gaussian kernel: log τ_ij = -0.5 · Σ_d diff²[i,j,d] / var_t[i,d]
        log_tau = -0.5 * np.einsum('ijd,id->ij', diff ** 2, 1.0 / var_t)   # (N, N)

        # Subtract per-column max for numerical stability before exp
        log_tau -= log_tau.max(axis=0, keepdims=True)
        tau = np.exp(log_tau)   # (N, N)

        # Normalizer: d_j = Σ_k w_t^k · τ_kj
        denom = w_t @ tau                    # (N,) shape N_j
        denom = np.maximum(denom, 1e-300)

        # Smoothed weight: s_t^i = w_t^i · Σ_j (s_{t+1}^j · τ_ij / d_j)
        ratio = tau / denom[np.newaxis, :]   # (N, N): τ_ij / d_j
        s_t   = w_t * (ratio @ smoothed[t + 1])   # (N,)

        s_t   = np.maximum(s_t, 0.0)
        s_sum = float(s_t.sum())
        smoothed[t] = s_t / s_sum if s_sum > 1e-300 else w_t.copy()

    return smoothed


def _particles_ter_tec_log10(positions_log10: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """
    Compute log10(TER) and log10(TEC) for N particles.

    positions_log10: (N, 5) log10 [Ra, Rb, Ca, Cb, Rsh]
    Returns: ter_log10 (N,), tec_log10 (N,)
    """
    p = 10.0 ** positions_log10
    Ra, Rb, Ca, Cb, Rsh = p[:, 0], p[:, 1], p[:, 2], p[:, 3], p[:, 4]
    TER = Rsh * (Ra + Rb) / (Rsh + Ra + Rb + 1e-30)
    TEC = Ca * Cb / (Ca + Cb + 1e-30)
    return np.log10(np.maximum(TER, 1.0)), np.log10(np.maximum(TEC, 1e-15))


def _ter_tec_jacobian_log10(pos_log10: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """
    Analytical d(log10 TER)/d(log10 theta) and d(log10 TEC)/d(log10 theta).

    Used to incorporate TER/TEC direct observations into the IEKF MAP gradient.

    pos_log10: (5,) log10 [Ra, Rb, Ca, Cb, Rsh]
    Returns: J_ter (5,), J_tec (5,)

    Derivations
    -----------
    TER = Rsh*(Ra+Rb)/(Rsh+Ra+Rb),  S = Rsh+Ra+Rb
      dTER/dRa  = Rsh^2/S^2
      dTER/dRb  = Rsh^2/S^2
      dTER/dRsh = (Ra+Rb)^2/S^2
      d(log10 TER)/d(log10 Ra) = Ra/(TER·ln10) · dTER/dRa

    TEC = Ca*Cb/(Ca+Cb),  T = Ca+Cb
      dTEC/dCa = Cb^2/T^2
      dTEC/dCb = Ca^2/T^2
    """
    p = 10.0 ** pos_log10
    Ra, Rb, Ca, Cb, Rsh = p
    ln10 = np.log(10.0)
    S = Rsh + Ra + Rb + 1e-30
    T = Ca + Cb + 1e-30
    TER = Rsh * (Ra + Rb) / S
    TEC = Ca * Cb / T

    c_ter = 1.0 / (TER * ln10 + 1e-300)
    J_ter = np.array([
        Ra  * Rsh ** 2 / S ** 2 * c_ter,      # d(log10 TER)/d(log10 Ra)
        Rb  * Rsh ** 2 / S ** 2 * c_ter,      # d(log10 TER)/d(log10 Rb)
        0.0,                                    # Ca: TER independent of capacitances
        0.0,                                    # Cb
        Rsh * (Ra + Rb) ** 2 / S ** 2 * c_ter, # d(log10 TER)/d(log10 Rsh)
    ])

    c_tec = 1.0 / (TEC * ln10 + 1e-300)
    J_tec = np.array([
        0.0,                                   # Ra: TEC independent of resistances
        0.0,                                   # Rb
        Ca * Cb ** 2 / T ** 2 * c_tec,        # d(log10 TEC)/d(log10 Ca)
        Cb * Ca ** 2 / T ** 2 * c_tec,        # d(log10 TEC)/d(log10 Cb)
        0.0,                                   # Rsh
    ])

    return J_ter, J_tec


def _ter_tec_jacobian_log10_batch(pos_log10: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """
    Batched analytical Jacobians for N particles simultaneously.

    pos_log10: (N, 5) log10 [Ra, Rb, Ca, Cb, Rsh]
    Returns: J_ter (N, 5), J_tec (N, 5)
    """
    p   = 10.0 ** pos_log10                   # (N, 5)
    Ra  = p[:, 0]; Rb  = p[:, 1]
    Ca  = p[:, 2]; Cb  = p[:, 3]; Rsh = p[:, 4]
    ln10 = np.log(10.0)
    S = Rsh + Ra + Rb + 1e-30
    T = Ca + Cb + 1e-30
    TER = Rsh * (Ra + Rb) / S
    TEC = Ca * Cb / T

    c_ter = 1.0 / (TER * ln10 + 1e-300)      # (N,)
    J_ter = np.zeros_like(pos_log10)
    J_ter[:, 0] = Ra  * Rsh**2 / S**2 * c_ter
    J_ter[:, 1] = Rb  * Rsh**2 / S**2 * c_ter
    J_ter[:, 4] = Rsh * (Ra + Rb)**2 / S**2 * c_ter

    c_tec = 1.0 / (TEC * ln10 + 1e-300)
    J_tec = np.zeros_like(pos_log10)
    J_tec[:, 2] = Ca * Cb**2 / T**2 * c_tec
    J_tec[:, 3] = Cb * Ca**2 / T**2 * c_tec

    return J_ter, J_tec


def _enforce_ordering_inplace(positions: np.ndarray) -> None:
    """
    Enforce Ra > Rb and Ca > Cb (in log10 space) for all particles in-place.

    Particles violating the ordering are corrected by swapping the relevant pair.
    This collapses the Ra↔Rb bimodal symmetry to a single mode consistent with
    the biological prior (apical membrane: Ra > Rb, Ca > Cb).
    """
    swap_r = positions[:, 0] < positions[:, 1]
    if swap_r.any():
        tmp = positions[swap_r, 0].copy()
        positions[swap_r, 0] = positions[swap_r, 1]
        positions[swap_r, 1] = tmp

    swap_c = positions[:, 2] < positions[:, 3]
    if swap_c.any():
        tmp = positions[swap_c, 2].copy()
        positions[swap_c, 2] = positions[swap_c, 3]
        positions[swap_c, 3] = tmp


def _invert_id_to_raw(
    id_log10: np.ndarray,
    big_tau_is_Ra: bool,
) -> Optional[np.ndarray]:
    """
    Algebraic inversion: identifiable log10 → raw log10, one mode.

    id_log10: (5,) log10 [tau_big, tau_small, TER, TEC, Rsh]
    big_tau_is_Ra: True  → mode 0 (Ra*Ca = tau_big)
                   False → mode 1 (Rb*Cb = tau_big)

    Returns (5,) log10 [Ra, Rb, Ca, Cb, Rsh] clipped to bounds, or None if
    the configuration is singular or outside physiological bounds.

    Derivation
    ----------
    TER = Rsh*(Ra+Rb)/(Rsh+Ra+Rb)  →  S_R = Ra+Rb = TER*Rsh/(Rsh-TER)
    TEC = Ca*Cb/(Ca+Cb)

    Mode 0: tau_big = Ra*Ca, tau_small = Rb*Cb
      Ca = tau_big/Ra, Cb = tau_small/Rb = tau_small/(S_R-Ra)
      TEC = Ca*Cb/(Ca+Cb) = tau_big*tau_small / (tau_big*S_R + Ra*(tau_small-tau_big))
      → Ra = tau_big*(tau_small - TEC*S_R) / (TEC*(tau_small - tau_big))
    """
    tau_big, tau_small, TER, TEC, Rsh = [10.0 ** float(id_log10[i]) for i in range(5)]

    # Guard: Rsh must exceed TER (parallel combination)
    if Rsh <= TER * 1.0001:
        return None

    S_R = TER * Rsh / (Rsh - TER)   # Ra + Rb  (always positive when Rsh > TER)
    if S_R <= 0:
        return None

    # Guard: tau_big must exceed tau_small (by construction, but check numerics)
    if tau_big <= tau_small * 1.001:
        return None

    denom = TEC * (tau_small - tau_big)   # negative
    if abs(denom) < 1e-30:
        return None

    Ra_big = tau_big * (tau_small - TEC * S_R) / denom

    # Ra_big must be in (0, S_R)
    if Ra_big <= 0 or Ra_big >= S_R:
        return None

    Rb_big = S_R - Ra_big
    Ca_big = tau_big  / Ra_big
    Cb_big = tau_small / Rb_big

    if Ca_big <= 0 or Cb_big <= 0:
        return None

    # Assign Ra/Rb, Ca/Cb based on mode
    if big_tau_is_Ra:
        Ra, Rb, Ca, Cb = Ra_big, Rb_big, Ca_big, Cb_big
    else:
        Ra, Rb, Ca, Cb = Rb_big, Ra_big, Cb_big, Ca_big

    raw = np.array([
        np.log10(Ra), np.log10(Rb),
        np.log10(Ca), np.log10(Cb),
        np.log10(Rsh),
    ], dtype=np.float64)

    # Clip to parameter bounds; return None if too far outside
    if np.any(raw < BOUNDS_LOW - 0.5) or np.any(raw > BOUNDS_HIGH + 0.5):
        return None

    return np.clip(raw, BOUNDS_LOW, BOUNDS_HIGH)


class GaussianParticleFilter:
    """
    Gaussian Particle Filter (GPF) for EIS parameter tracking.

    Each particle carries a local Gaussian (mean + covariance) updated via an
    iterated EKF (IEKF) observation step; the ensemble forms a Gaussian mixture.
    Global velocity estimate from weighted mean displacement for prediction.

    Position-only state per particle (no velocity cross-covariance).
    Why position-only: the constant-velocity Kalman per particle requires tracking
    P_pv (position-velocity cross-covariance). When sigma2 is small (data-rich),
    G = K_pos @ J has eigenvalues in [0,1] but diagonal entries can be far outside
    this range due to off-diagonal structure in Q_vel. This makes (I-G) @ P_pv blow up,
    driving unstable velocity estimates. Position-only EKF avoids this entirely.
    """

    def __init__(
        self,
        n_particles: int = 64,
        noise_snr_db: float = 40.0,
        min_ess_frac: float = 0.5,
        jitter_after_resample_std: float = 0.02,
        n_iekf_iter: int = 2,
        enforce_ordering: bool = True,
        ter_obs_sigma_log10: float = 0.015,
        tec_obs_sigma_log10: float = 0.05,
    ):
        self.N = n_particles
        self.sigma2 = 10 ** (-noise_snr_db / 10.0)   # normalized noise variance
        self.min_ess_frac = min_ess_frac
        self.jitter_std = jitter_after_resample_std
        self.n_iekf_iter = max(1, int(n_iekf_iter))   # 1 = standard EKF, 2+ = IEKF

        # Ordering constraint: Ra > Rb and Ca > Cb (apical > basolateral prior)
        self.enforce_ordering = enforce_ordering

        # TER/TEC direct observation noise (log10 decades).
        # TER_obs = Z_real[lowest freq] ≈ DC limit.  sigma=0.015 ≈ 3.5% fractional.
        # TEC_obs = -1/(omega_max * Z_imag[highest freq]).  sigma=0.05 ≈ 12% fractional.
        self._ter_sigma2_log10 = ter_obs_sigma_log10 ** 2
        self._tec_sigma2_log10 = tec_obs_sigma_log10 ** 2

        # Particle state — allocated at initialize()
        self.positions: np.ndarray = np.empty((n_particles, 5))
        self.P_pp: np.ndarray     = np.zeros((n_particles, 5, 5))
        self.log_w: np.ndarray    = np.full(n_particles, -np.log(n_particles))

        # Global velocity estimate (weighted mean displacement per unit time)
        self._prev_wtd_mean: Optional[np.ndarray] = None
        self._global_vel: np.ndarray = np.zeros(5)

        self._initialized = False

    # ------------------------------------------------------------------
    # Initialization
    # ------------------------------------------------------------------

    def initialize(
        self,
        ecm_log10: Optional[np.ndarray] = None,
        mdn_samples: Optional[np.ndarray] = None,
        mdn_means_id: Optional[np.ndarray] = None,
        mdn_weights: Optional[np.ndarray] = None,
        P_pp_init_std: float = 0.3,
    ) -> None:
        """
        Initialize N particles.

        When enforce_ordering=True (default): all particles are drawn from a single
        mode with Ra > Rb and Ca > Cb enforced. The biological prior eliminates the
        Ra↔Rb ambiguity so mode stratification is unnecessary.

        When enforce_ordering=False: 50/50 mode split for both permutations.

        Priority order:
          1. ecm_log10  — ECM raw params as center (most accurate per-step estimate).
          2. mdn_means_id + mdn_weights  — algebraic inversion of MDN component means.
          3. mdn_samples — median of raw MDN samples (legacy fallback).
          4. BOUNDS_MID  — uniform cold start.

        Parameters
        ----------
        ecm_log10 : (5,) log10 [Ra,Rb,Ca,Cb,Rsh]
        mdn_samples : (M, 5) log10 raw (legacy)
        mdn_means_id : (K, 5) log10 identifiable [tau_big,tau_small,TER,TEC,Rsh]
        mdn_weights : (K,) softmax mixture weights
        P_pp_init_std : std of initial per-particle position covariance (log10)
        """
        N = self.N

        def _sample_around(center_raw: np.ndarray, n: int, std: float) -> np.ndarray:
            pts = center_raw + np.random.randn(n, 5) * std
            return np.clip(pts, BOUNDS_LOW, BOUNDS_HIGH)

        def _two_mode_particles(center_raw: np.ndarray, n: int, std: float) -> np.ndarray:
            """50/50 split: direct center and Ra↔Rb,Ca↔Cb swapped center."""
            half = n // 2
            direct  = _sample_around(center_raw, half, std)
            swapped_ctr = center_raw.copy()
            swapped_ctr[[0, 1]] = center_raw[[1, 0]]
            swapped_ctr[[2, 3]] = center_raw[[3, 2]]
            swapped = _sample_around(swapped_ctr, n - half, std)
            return np.vstack([direct, swapped])

        positions: Optional[np.ndarray] = None

        # ── Priority 1: ECM raw center ────────────────────────────────────────
        if ecm_log10 is not None:
            ctr = np.clip(ecm_log10, BOUNDS_LOW, BOUNDS_HIGH)
            if self.enforce_ordering:
                # Enforce ordering on the center itself before sampling
                _enforce_ordering_inplace(ctr[np.newaxis, :])
                ctr = ctr.ravel()
                positions = _sample_around(ctr, N, 0.12)
            else:
                positions = _two_mode_particles(ctr, N, 0.12)

        # ── Priority 2: MDN identifiable means → algebraic inversion ──────────
        if positions is None and mdn_means_id is not None and len(mdn_means_id) > 0:
            K = len(mdn_means_id)
            w = np.ones(K) / K if mdn_weights is None else np.asarray(mdn_weights, dtype=np.float64)
            w = np.clip(w, 0, None)
            w /= w.sum() + 1e-12

            centers: list[tuple[np.ndarray, float]] = []
            for k in range(K):
                for mode in (True, False):
                    r = _invert_id_to_raw(mdn_means_id[k], big_tau_is_Ra=mode)
                    if r is not None:
                        centers.append((r, float(w[k]) / 2))

            if centers:
                wts = np.array([c[1] for c in centers])
                wts /= wts.sum()
                counts = np.round(wts * N).astype(int)
                diff = N - int(counts.sum())
                counts[np.argmax(wts)] += diff
                pts = []
                for (ctr, _), n_k in zip(centers, counts):
                    if n_k > 0:
                        pts.append(_sample_around(ctr, n_k, 0.12))
                if pts:
                    positions = np.vstack(pts)

        # ── Priority 3: MDN raw samples median ────────────────────────────────
        if positions is None and mdn_samples is not None and len(mdn_samples) > 0:
            ctr = np.clip(np.median(mdn_samples, axis=0), BOUNDS_LOW, BOUNDS_HIGH)
            if self.enforce_ordering:
                _enforce_ordering_inplace(ctr[np.newaxis, :])
                ctr = ctr.ravel()
                positions = _sample_around(ctr, N, 0.15)
            else:
                positions = _two_mode_particles(ctr, N, 0.15)

        # ── Priority 4: cold start from healthy biological prior ──────────────
        # _HEALTHY_CENTER_LOG10 is far more informative than BOUNDS_MID.
        # Rsh gets a wider spread (0.6 vs 0.3 std) because the healthy center is
        # 4.12 log10 but pathological Rsh can be as low as 1.7 — a 2.4-decade gap
        # that 0.3 std particles can't bridge in a few steps.
        if positions is None:
            ctr = _HEALTHY_CENTER_LOG10.copy()
            if self.enforce_ordering:
                pts = np.random.randn(N, 5) * np.array([0.3, 0.3, 0.3, 0.3, 0.6])
                positions = np.clip(ctr + pts, BOUNDS_LOW, BOUNDS_HIGH)
            else:
                positions = _two_mode_particles(ctr, N, 0.3)

        # ── Pad / trim to exactly N ───────────────────────────────────────────
        if len(positions) < N:
            deficit = N - len(positions)
            extras = positions[np.random.choice(len(positions), deficit)] \
                     + np.random.randn(deficit, 5) * 0.05
            positions = np.vstack([positions, np.clip(extras, BOUNDS_LOW, BOUNDS_HIGH)])
        elif len(positions) > N:
            positions = positions[:N]

        # ── Enforce ordering on all initial particles ─────────────────────────
        if self.enforce_ordering:
            _enforce_ordering_inplace(positions)

        self.positions = positions
        self.log_w[:] = -np.log(N)

        P_pp_0 = np.diag(np.full(5, P_pp_init_std ** 2))
        for i in range(N):
            self.P_pp[i] = P_pp_0.copy()

        self._prev_wtd_mean = None
        self._global_vel[:] = 0.0
        self._initialized = True

    # ------------------------------------------------------------------
    # Process model: predict step
    # ------------------------------------------------------------------

    def _predict(self, dt: float) -> None:
        """
        Predict particle positions forward by dt minutes.

        Three additive contributions (Euler-Maruyama in log10 space):
          1. Global velocity drift   — tracks slow parameter trends
          2. Biological mean-reversion — weak pull toward healthy RPE priors
          3. Diagonal process noise  — maintains particle diversity

        The biological term uses _BIO_KAPPA ~ 1e-4 /min, ~100× weaker than
        typical measurement information, so it only matters during data gaps.
        """
        Q_step = _Q_POS_DIAG * dt
        Q_std  = np.sqrt(Q_step)

        # Global velocity from previous weighted-mean displacement
        vel_drift = self._global_vel * dt

        # Weak biological mean-reversion toward healthy RPE center (OU-style)
        bio_drift = (_BIO_KAPPA * (_HEALTHY_CENTER_LOG10 - self.positions)) * dt

        noise = np.random.randn(self.N, 5) * Q_std[np.newaxis, :]
        self.positions += vel_drift[np.newaxis, :] + bio_drift + noise
        self.positions = np.clip(self.positions, BOUNDS_LOW, BOUNDS_HIGH)

        # Inflate position covariance with process noise
        self.P_pp += np.diag(Q_step)

    # ------------------------------------------------------------------
    # EKF observation update + weight computation
    # ------------------------------------------------------------------

    def _update_and_weight(
        self,
        Z_r_obs: np.ndarray,
        Z_i_obs: np.ndarray,
        omega: np.ndarray,
    ) -> float:
        """
        Vectorized IEKF update and log-weight accumulation for all N particles.

        All per-particle matrix operations (inv, slogdet, einsum) are batched
        across the N dimension using numpy's batched LAPACK interface, replacing
        the previous sequential for-loop over particles.

        Weight factorization (evaluated at the prior position):
          log w_i += log p(Z_spectral | theta_i)  [Woodbury, (N,5,5) batch]
                   + log p(TER_obs | theta_i)     [Gaussian in log10]
                   + log p(TEC_obs | theta_i)     [Gaussian in log10]

        IEKF update (anchored to theta_prior, all particles in batch):
          theta_{k+1} = theta_prior + M_k^{-1} @ (Jte_eff_k + JtRinvJ_k @ delta_k)
        """
        N = self.N
        F = len(omega)
        sigma2 = self.sigma2

        # ── Normalize spectral observations ───────────────────────────────────
        norm_r = float(np.max(np.abs(Z_r_obs))) + 1e-20
        norm_i = float(np.max(np.abs(Z_i_obs))) + 1e-20
        Z_r_norm = (Z_r_obs / norm_r).astype(np.float64)
        Z_i_norm = (Z_i_obs / norm_i).astype(np.float64)

        # ── TER/TEC direct spectral observations ─────────────────────────────
        idx_low = int(np.argmin(omega))
        TER_obs_log10 = float(np.log10(max(Z_r_obs[idx_low], 1.0)))
        idx_high = int(np.argmax(omega))
        zi_high  = float(Z_i_obs[idx_high])
        if zi_high < -1e-10:
            TEC_obs_log10 = float(np.log10(max(-1.0 / (omega[idx_high] * zi_high), 1e-15)))
            tec_valid = True
        else:
            TEC_obs_log10 = 0.0
            tec_valid = False

        ter_s2 = self._ter_sigma2_log10
        tec_s2 = self._tec_sigma2_log10

        # ── Batch impedance, residuals, Jacobians at prior ────────────────────
        Zr0, Zi0 = _impedance_batch_numpy(self.positions, omega)
        e0 = np.concatenate([
            Z_r_norm[np.newaxis, :] - Zr0 / norm_r,
            Z_i_norm[np.newaxis, :] - Zi0 / norm_i,
        ], axis=1)  # (N, 2F)
        J0 = _jacobian_numerical(self.positions, omega, norm_r, norm_i)  # (N, 2F, 5)

        # ── Batch TER/TEC priors and Jacobians ───────────────────────────────
        ter_prior, tec_prior = _particles_ter_tec_log10(self.positions)  # (N,)
        J_ter0, J_tec0 = _ter_tec_jacobian_log10_batch(self.positions)   # (N, 5)
        e_ter0 = TER_obs_log10 - ter_prior                                # (N,)

        # ── Batch P_pp inverse ───────────────────────────────────────────────
        P_pp_inv = np.linalg.inv(self.P_pp)   # (N, 5, 5) — single LAPACK call

        # ── Batch weight computation (Woodbury, vectorized) ───────────────────
        JtJ  = np.einsum('nfi,nfj->nij', J0, J0)         # (N, 5, 5)
        Jte  = np.einsum('nfi,nf->ni',   J0, e0)          # (N, 5)
        M_sp = P_pp_inv + JtJ / sigma2                     # (N, 5, 5)
        M_sp_inv = np.linalg.inv(M_sp)                    # (N, 5, 5)

        e_sq            = np.sum(e0 ** 2, axis=1) / sigma2                          # (N,)
        Jte_MInv_Jte   = np.einsum('ni,nij,nj->n', Jte, M_sp_inv, Jte) / sigma2**2 # (N,)
        mahal           = e_sq - Jte_MInv_Jte                                        # (N,)

        sign_M, logdet_M = np.linalg.slogdet(M_sp)        # (N,)  batch
        sign_P, logdet_P = np.linalg.slogdet(self.P_pp)   # (N,)  batch

        log_w_inc = -0.5 * (mahal + logdet_M + logdet_P
                            + 2*F*np.log(sigma2+1e-300) + 2*F*_LOG_2PI)
        bad = (sign_M <= 0) | (sign_P <= 0) | ~np.isfinite(log_w_inc)
        log_w_inc[bad] = -1e6

        log_norm_ter = 0.5 * np.log(2 * np.pi * ter_s2)
        log_w_inc -= 0.5 * e_ter0 ** 2 / ter_s2 + log_norm_ter

        if tec_valid:
            e_tec0 = TEC_obs_log10 - tec_prior
            log_norm_tec = 0.5 * np.log(2 * np.pi * tec_s2)
            log_w_inc -= 0.5 * e_tec0 ** 2 / tec_s2 + log_norm_tec

        # ── Batch IEKF MAP update ─────────────────────────────────────────────
        JtRinvJ = JtJ / sigma2 + np.einsum('ni,nj->nij', J_ter0, J_ter0) / ter_s2
        Jte_eff = Jte / sigma2 + J_ter0 * e_ter0[:, None] / ter_s2

        if tec_valid:
            e_tec0_v = e_tec0[:, None]
            JtRinvJ += np.einsum('ni,nj->nij', J_tec0, J_tec0) / tec_s2
            Jte_eff  += J_tec0 * e_tec0_v / tec_s2

        M_aug     = P_pp_inv + JtRinvJ                     # (N, 5, 5)
        M_aug_inv = np.linalg.inv(M_aug)                   # (N, 5, 5)

        theta_prior = self.positions.copy()
        # First IEKF pass (k=0): correction term = 0
        theta_k = np.clip(
            theta_prior + np.einsum('nij,nj->ni', M_aug_inv, Jte_eff),
            BOUNDS_LOW, BOUNDS_HIGH,
        )
        P_post = M_aug_inv.copy()

        # IEKF relinearization passes (fully batch across N)
        for _ in range(self.n_iekf_iter - 1):
            Zr_k, Zi_k = _impedance_batch_numpy(theta_k, omega)
            e_k = np.concatenate([
                Z_r_norm[np.newaxis, :] - Zr_k / norm_r,
                Z_i_norm[np.newaxis, :] - Zi_k / norm_i,
            ], axis=1)  # (N, 2F)
            J_k = _jacobian_numerical(theta_k, omega, norm_r, norm_i)   # (N, 2F, 5)

            ter_k, tec_k = _particles_ter_tec_log10(theta_k)
            J_ter_k, J_tec_k = _ter_tec_jacobian_log10_batch(theta_k)
            e_ter_k = TER_obs_log10 - ter_k                              # (N,)

            JtJ_k     = np.einsum('nfi,nfj->nij', J_k, J_k)
            Jte_k     = np.einsum('nfi,nf->ni',   J_k, e_k)
            JtRinvJ_k = JtJ_k / sigma2 + np.einsum('ni,nj->nij', J_ter_k, J_ter_k) / ter_s2
            Jte_eff_k = Jte_k / sigma2 + J_ter_k * e_ter_k[:, None] / ter_s2

            if tec_valid:
                e_tec_k = TEC_obs_log10 - tec_k
                JtRinvJ_k += np.einsum('ni,nj->nij', J_tec_k, J_tec_k) / tec_s2
                Jte_eff_k  += J_tec_k * e_tec_k[:, None] / tec_s2

            M_k     = P_pp_inv + JtRinvJ_k
            M_k_inv = np.linalg.inv(M_k)

            delta   = theta_k - theta_prior                               # (N, 5)
            corr    = np.einsum('nij,nj->ni', JtRinvJ_k, delta)
            theta_k = np.clip(
                theta_prior + np.einsum('nij,nj->ni', M_k_inv, Jte_eff_k + corr),
                BOUNDS_LOW, BOUNDS_HIGH,
            )
            P_post = M_k_inv

        self.positions = theta_k
        for i in range(N):
            self.P_pp[i] = _ensure_psd(P_post[i])

        if self.enforce_ordering:
            _enforce_ordering_inplace(self.positions)

        self.log_w += log_w_inc

        finite = log_w_inc[np.isfinite(log_w_inc)]
        if len(finite) == 0:
            return -1e6
        lmax = float(np.max(finite))
        return float(lmax + np.log(np.mean(np.exp(finite - lmax))))

    # ------------------------------------------------------------------
    # Global velocity update
    # ------------------------------------------------------------------

    def _update_global_vel(self, dt: float) -> None:
        """
        Estimate global velocity from weighted mean displacement since last step.
        This allows the filter to track slow parameter trends without per-particle
        velocity states.
        """
        w = self.get_weights()
        cur_mean = (w[:, None] * self.positions).sum(axis=0)

        if self._prev_wtd_mean is not None and dt > 1e-6:
            raw_vel = (cur_mean - self._prev_wtd_mean) / dt
            # Low-pass filter: blend new estimate with previous (alpha controls responsiveness)
            alpha = min(1.0, dt / 5.0)   # 5-minute time constant
            self._global_vel = (1 - alpha) * self._global_vel + alpha * raw_vel

        self._prev_wtd_mean = cur_mean.copy()

    # ------------------------------------------------------------------
    # Resampling
    # ------------------------------------------------------------------

    def _resample(self) -> None:
        """
        Systematic resampling when ESS < N * min_ess_frac.
        After resampling, add jitter to maintain diversity.
        """
        log_w = self.log_w.copy()
        log_w[~np.isfinite(log_w)] = -1e300
        log_w -= np.max(log_w)
        w = np.exp(log_w)
        w /= w.sum()

        ess = 1.0 / float(np.sum(w ** 2))
        if ess >= self.N * self.min_ess_frac:
            return

        N = self.N
        cumsum = np.cumsum(w)
        u = (np.arange(N) + np.random.uniform()) / N
        idx = np.searchsorted(cumsum, u)
        idx = np.clip(idx, 0, N - 1)

        self.positions = self.positions[idx]
        self.P_pp      = self.P_pp[idx]

        # Jitter positions slightly to avoid particle collapse
        pos_jitter = np.random.randn(N, 5) * self.jitter_std
        self.positions = np.clip(self.positions + pos_jitter, BOUNDS_LOW, BOUNDS_HIGH)

        # Restore ordering after jitter (jitter can push Ra < Rb)
        if self.enforce_ordering:
            _enforce_ordering_inplace(self.positions)

        self.log_w[:] = -np.log(N)

    # ------------------------------------------------------------------
    # Main step
    # ------------------------------------------------------------------

    def step(
        self,
        Z_r_obs: np.ndarray,
        Z_i_obs: np.ndarray,
        omega: np.ndarray,
        dt: float = 1.0,
    ) -> tuple[np.ndarray, float]:
        """
        One GPF step: predict -> update -> resample.

        Args:
            Z_r_obs: (F,) observed real impedance (raw Ohms)
            Z_i_obs: (F,) observed imaginary impedance (raw Ohms)
            omega:   (F,) angular frequencies (rad/s)
            dt:      time since last measurement (minutes)

        Returns:
            particles: (N, 5) current particle positions in log10 raw space
            log_evidence: float, log p(Z_t | Z_{1:t-1})
        """
        if not self._initialized:
            raise RuntimeError("Call initialize() before step()")

        dt = max(float(dt), 1e-3)

        self._predict(dt)
        log_evidence = self._update_and_weight(Z_r_obs, Z_i_obs, omega)
        self._update_global_vel(dt)
        self._resample()

        return self.positions.copy(), log_evidence

    # ------------------------------------------------------------------
    # Accessors and diagnostics
    # ------------------------------------------------------------------

    def get_particles(self) -> np.ndarray:
        """Return current particle positions (N, 5) in log10 raw space."""
        return self.positions.copy()

    def get_weights(self) -> np.ndarray:
        """Return normalized particle weights (N,)."""
        log_w = self.log_w.copy()
        log_w[~np.isfinite(log_w)] = -1e300
        log_w -= np.max(log_w)
        w = np.exp(log_w)
        return w / w.sum()

    def get_ess(self) -> float:
        """Effective sample size."""
        w = self.get_weights()
        return float(1.0 / np.sum(w ** 2))

    def get_diagnostics(self) -> dict:
        """Diagnostics for streaming display and frontend version badges."""
        p = self.positions
        w = self.get_weights()
        p_ca_gt_cb = float(np.sum(w * (p[:, 2] > p[:, 3]).astype(float)))
        p_ra_lt_rb = float(np.sum(w * (p[:, 0] < p[:, 1]).astype(float)))

        # Weighted mean position and its biological deviation from healthy center
        wtd_mean = (w[:, None] * p).sum(axis=0)
        bio_deviation = float(np.linalg.norm(wtd_mean - _HEALTHY_CENTER_LOG10))

        # Rsh deviation in log10 decades (key clinical indicator)
        rsh_deviation = float(wtd_mean[4] - _HEALTHY_CENTER_LOG10[4])

        return {
            'version':       GPF_VERSION,
            'ess_frac':      self.get_ess() / self.N,
            'p_Ca_gt_Cb':    p_ca_gt_cb,
            'p_Ra_lt_Rb':    p_ra_lt_rb,
            'global_vel':    self._global_vel.tolist(),
            'bio_deviation': bio_deviation,
            'rsh_deviation': rsh_deviation,
            'bounds_low':    BOUNDS_LOW.tolist(),
            'bounds_high':   BOUNDS_HIGH.tolist(),
            'healthy_center': _HEALTHY_CENTER_LOG10.tolist(),
        }
